Text_ThunderWaveTeach::
    .string "Eeek!\n"
    .string "No! Stop! Help!\p"
    .string "Oh, you're not with TEAM ROCKET.\n"
    .string "I'm sorry, I thought…\p"
    .string "Will you forgive me if I teach\n"
    .string "you the THUNDER WAVE technique?$"

Text_ThunderWaveDeclined::
    .string "Oh…\n"
    .string "But THUNDER WAVE is convenient…$"

Text_ThunderWaveWhichMon::
    .string "Which POKéMON should I teach\n"
    .string "THUNDER WAVE?$"

Text_ThunderWaveTaught::
    .string "THUNDER WAVE causes paralysis in\n"
    .string "the target POKéMON.\p"
    .string "A paralyzed POKéMON may be unable\n"
    .string "to move in battle.\p"
    .string "It's an ELECTRIC-type move, so it\n"
    .string "won't work on some POKéMON.$"
