#ifndef GUARD_CONSTANTS_POKEDEX_H
#define GUARD_CONSTANTS_POKEDEX_H


#define FOREACH_SPECIES_IN_NATIONAL_DEX(F) \
    F(NONE) \
    F(BULBASAUR) \
    F(IVYSAUR) \
    F(VENUSAUR) \
    F(CHARMANDER) \
    F(CHARMELEON) \
    F(CHARIZARD) \
    F(SQUIRTLE) \
    F(WARTORTLE) \
    F(BLASTOISE) \
    F(CATERPIE) \
    F(METAPOD) \
    F(BUTTERFREE) \
    F(WEEDLE) \
    F(KAKUNA) \
    F(BEEDRILL) \
    F(PIDGEY) \
    F(PIDGEOTTO) \
    F(PIDGEOT) \
    F(RATTATA) \
    F(RATICATE) \
    F(SPEAROW) \
    F(FEAROW) \
    F(EKANS) \
    F(ARBOK) \
    F(PIKACHU) \
    F(RAICHU) \
    F(SANDSHREW) \
    F(SANDSLASH) \
    F(NIDORAN_F) \
    F(NIDORINA) \
    F(NIDOQUEEN) \
    F(NIDORAN_M) \
    F(NIDORINO) \
    F(NIDOKING) \
    F(CLEFAIRY) \
    F(CLEFABLE) \
    F(VULPIX) \
    F(NINETALES) \
    F(JIGGLYPUFF) \
    F(WIGGLYTUFF) \
    F(ZUBAT) \
    F(GOLBAT) \
    F(ODDISH) \
    F(GLOOM) \
    F(VILEPLUME) \
    F(PARAS) \
    F(PARASECT) \
    F(VENONAT) \
    F(VENOMOTH) \
    F(DIGLETT) \
    F(DUGTRIO) \
    F(MEOWTH) \
    F(PERSIAN) \
    F(PSYDUCK) \
    F(GOLDUCK) \
    F(MANKEY) \
    F(PRIMEAPE) \
    F(GROWLITHE) \
    F(ARCANINE) \
    F(POLIWAG) \
    F(POLIWHIRL) \
    F(POLIWRATH) \
    F(ABRA) \
    F(KADABRA) \
    F(ALAKAZAM) \
    F(MACHOP) \
    F(MACHOKE) \
    F(MACHAMP) \
    F(BELLSPROUT) \
    F(WEEPINBELL) \
    F(VICTREEBEL) \
    F(TENTACOOL) \
    F(TENTACRUEL) \
    F(GEODUDE) \
    F(GRAVELER) \
    F(GOLEM) \
    F(PONYTA) \
    F(RAPIDASH) \
    F(SLOWPOKE) \
    F(SLOWBRO) \
    F(MAGNEMITE) \
    F(MAGNETON) \
    F(FARFETCHD) \
    F(DODUO) \
    F(DODRIO) \
    F(SEEL) \
    F(DEWGONG) \
    F(GRIMER) \
    F(MUK) \
    F(SHELLDER) \
    F(CLOYSTER) \
    F(GASTLY) \
    F(HAUNTER) \
    F(GENGAR) \
    F(ONIX) \
    F(DROWZEE) \
    F(HYPNO) \
    F(KRABBY) \
    F(KINGLER) \
    F(VOLTORB) \
    F(ELECTRODE) \
    F(EXEGGCUTE) \
    F(EXEGGUTOR) \
    F(CUBONE) \
    F(MAROWAK) \
    F(HITMONLEE) \
    F(HITMONCHAN) \
    F(LICKITUNG) \
    F(KOFFING) \
    F(WEEZING) \
    F(RHYHORN) \
    F(RHYDON) \
    F(CHANSEY) \
    F(TANGELA) \
    F(KANGASKHAN) \
    F(HORSEA) \
    F(SEADRA) \
    F(GOLDEEN) \
    F(SEAKING) \
    F(STARYU) \
    F(STARMIE) \
    F(MR_MIME) \
    F(SCYTHER) \
    F(JYNX) \
    F(ELECTABUZZ) \
    F(MAGMAR) \
    F(PINSIR) \
    F(TAUROS) \
    F(MAGIKARP) \
    F(GYARADOS) \
    F(LAPRAS) \
    F(DITTO) \
    F(EEVEE) \
    F(VAPOREON) \
    F(JOLTEON) \
    F(FLAREON) \
    F(PORYGON) \
    F(OMANYTE) \
    F(OMASTAR) \
    F(KABUTO) \
    F(KABUTOPS) \
    F(AERODACTYL) \
    F(SNORLAX) \
    F(ARTICUNO) \
    F(ZAPDOS) \
    F(MOLTRES) \
    F(DRATINI) \
    F(DRAGONAIR) \
    F(DRAGONITE) \
    F(MEWTWO) \
    F(MEW) \
    F(CHIKORITA) \
    F(BAYLEEF) \
    F(MEGANIUM) \
    F(CYNDAQUIL) \
    F(QUILAVA) \
    F(TYPHLOSION) \
    F(TOTODILE) \
    F(CROCONAW) \
    F(FERALIGATR) \
    F(SENTRET) \
    F(FURRET) \
    F(HOOTHOOT) \
    F(NOCTOWL) \
    F(LEDYBA) \
    F(LEDIAN) \
    F(SPINARAK) \
    F(ARIADOS) \
    F(CROBAT) \
    F(CHINCHOU) \
    F(LANTURN) \
    F(PICHU) \
    F(CLEFFA) \
    F(IGGLYBUFF) \
    F(TOGEPI) \
    F(TOGETIC) \
    F(NATU) \
    F(XATU) \
    F(MAREEP) \
    F(FLAAFFY) \
    F(AMPHAROS) \
    F(BELLOSSOM) \
    F(MARILL) \
    F(AZUMARILL) \
    F(SUDOWOODO) \
    F(POLITOED) \
    F(HOPPIP) \
    F(SKIPLOOM) \
    F(JUMPLUFF) \
    F(AIPOM) \
    F(SUNKERN) \
    F(SUNFLORA) \
    F(YANMA) \
    F(WOOPER) \
    F(QUAGSIRE) \
    F(ESPEON) \
    F(UMBREON) \
    F(MURKROW) \
    F(SLOWKING) \
    F(MISDREAVUS) \
    F(UNOWN) \
    F(WOBBUFFET) \
    F(GIRAFARIG) \
    F(PINECO) \
    F(FORRETRESS) \
    F(DUNSPARCE) \
    F(GLIGAR) \
    F(STEELIX) \
    F(SNUBBULL) \
    F(GRANBULL) \
    F(QWILFISH) \
    F(SCIZOR) \
    F(SHUCKLE) \
    F(HERACROSS) \
    F(SNEASEL) \
    F(TEDDIURSA) \
    F(URSARING) \
    F(SLUGMA) \
    F(MAGCARGO) \
    F(SWINUB) \
    F(PILOSWINE) \
    F(CORSOLA) \
    F(REMORAID) \
    F(OCTILLERY) \
    F(DELIBIRD) \
    F(MANTINE) \
    F(SKARMORY) \
    F(HOUNDOUR) \
    F(HOUNDOOM) \
    F(KINGDRA) \
    F(PHANPY) \
    F(DONPHAN) \
    F(PORYGON2) \
    F(STANTLER) \
    F(SMEARGLE) \
    F(TYROGUE) \
    F(HITMONTOP) \
    F(SMOOCHUM) \
    F(ELEKID) \
    F(MAGBY) \
    F(MILTANK) \
    F(BLISSEY) \
    F(RAIKOU) \
    F(ENTEI) \
    F(SUICUNE) \
    F(LARVITAR) \
    F(PUPITAR) \
    F(TYRANITAR) \
    F(LUGIA) \
    F(HO_OH) \
    F(CELEBI) \
    F(TREECKO) \
    F(GROVYLE) \
    F(SCEPTILE) \
    F(TORCHIC) \
    F(COMBUSKEN) \
    F(BLAZIKEN) \
    F(MUDKIP) \
    F(MARSHTOMP) \
    F(SWAMPERT) \
    F(POOCHYENA) \
    F(MIGHTYENA) \
    F(ZIGZAGOON) \
    F(LINOONE) \
    F(WURMPLE) \
    F(SILCOON) \
    F(BEAUTIFLY) \
    F(CASCOON) \
    F(DUSTOX) \
    F(LOTAD) \
    F(LOMBRE) \
    F(LUDICOLO) \
    F(SEEDOT) \
    F(NUZLEAF) \
    F(SHIFTRY) \
    F(TAILLOW) \
    F(SWELLOW) \
    F(WINGULL) \
    F(PELIPPER) \
    F(RALTS) \
    F(KIRLIA) \
    F(GARDEVOIR) \
    F(SURSKIT) \
    F(MASQUERAIN) \
    F(SHROOMISH) \
    F(BRELOOM) \
    F(SLAKOTH) \
    F(VIGOROTH) \
    F(SLAKING) \
    F(NINCADA) \
    F(NINJASK) \
    F(SHEDINJA) \
    F(WHISMUR) \
    F(LOUDRED) \
    F(EXPLOUD) \
    F(MAKUHITA) \
    F(HARIYAMA) \
    F(AZURILL) \
    F(NOSEPASS) \
    F(SKITTY) \
    F(DELCATTY) \
    F(SABLEYE) \
    F(MAWILE) \
    F(ARON) \
    F(LAIRON) \
    F(AGGRON) \
    F(MEDITITE) \
    F(MEDICHAM) \
    F(ELECTRIKE) \
    F(MANECTRIC) \
    F(PLUSLE) \
    F(MINUN) \
    F(VOLBEAT) \
    F(ILLUMISE) \
    F(ROSELIA) \
    F(GULPIN) \
    F(SWALOT) \
    F(CARVANHA) \
    F(SHARPEDO) \
    F(WAILMER) \
    F(WAILORD) \
    F(NUMEL) \
    F(CAMERUPT) \
    F(TORKOAL) \
    F(SPOINK) \
    F(GRUMPIG) \
    F(SPINDA) \
    F(TRAPINCH) \
    F(VIBRAVA) \
    F(FLYGON) \
    F(CACNEA) \
    F(CACTURNE) \
    F(SWABLU) \
    F(ALTARIA) \
    F(ZANGOOSE) \
    F(SEVIPER) \
    F(LUNATONE) \
    F(SOLROCK) \
    F(BARBOACH) \
    F(WHISCASH) \
    F(CORPHISH) \
    F(CRAWDAUNT) \
    F(BALTOY) \
    F(CLAYDOL) \
    F(LILEEP) \
    F(CRADILY) \
    F(ANORITH) \
    F(ARMALDO) \
    F(FEEBAS) \
    F(MILOTIC) \
    F(CASTFORM) \
    F(KECLEON) \
    F(SHUPPET) \
    F(BANETTE) \
    F(DUSKULL) \
    F(DUSCLOPS) \
    F(TROPIUS) \
    F(CHIMECHO) \
    F(ABSOL) \
    F(WYNAUT) \
    F(SNORUNT) \
    F(GLALIE) \
    F(SPHEAL) \
    F(SEALEO) \
    F(WALREIN) \
    F(CLAMPERL) \
    F(HUNTAIL) \
    F(GOREBYSS) \
    F(RELICANTH) \
    F(LUVDISC) \
    F(BAGON) \
    F(SHELGON) \
    F(SALAMENCE) \
    F(BELDUM) \
    F(METANG) \
    F(METAGROSS) \
    F(REGIROCK) \
    F(REGICE) \
    F(REGISTEEL) \
    F(LATIAS) \
    F(LATIOS) \
    F(KYOGRE) \
    F(GROUDON) \
    F(RAYQUAZA) \
    F(JIRACHI) \
    F(DEOXYS) \
    F(TURTWIG) \
    F(GROTLE) \
    F(TORTERRA) \
    F(CHIMCHAR) \
    F(MONFERNO) \
    F(INFERNAPE) \
    F(PIPLUP) \
    F(PRINPLUP) \
    F(EMPOLEON) \
    F(STARLY) \
    F(STARAVIA) \
    F(STARAPTOR) \
    F(BIDOOF) \
    F(BIBAREL) \
    F(KRICKETOT) \
    F(KRICKETUNE) \
    F(SHINX) \
    F(LUXIO) \
    F(LUXRAY) \
    F(BUDEW) \
    F(ROSERADE) \
    F(CRANIDOS) \
    F(RAMPARDOS) \
    F(SHIELDON) \
    F(BASTIODON) \
    F(BURMY) \
    F(WORMADAM) \
    F(MOTHIM) \
    F(COMBEE) \
    F(VESPIQUEN) \
    F(PACHIRISU) \
    F(BUIZEL) \
    F(FLOATZEL) \
    F(CHERUBI) \
    F(CHERRIM) \
    F(SHELLOS) \
    F(GASTRODON) \
    F(AMBIPOM) \
    F(DRIFLOON) \
    F(DRIFBLIM) \
    F(BUNEARY) \
    F(LOPUNNY) \
    F(MISMAGIUS) \
    F(HONCHKROW) \
    F(GLAMEOW) \
    F(PURUGLY) \
    F(CHINGLING) \
    F(STUNKY) \
    F(SKUNTANK) \
    F(BRONZOR) \
    F(BRONZONG) \
    F(BONSLY) \
    F(MIME_JR) \
    F(HAPPINY) \
    F(CHATOT) \
    F(SPIRITOMB) \
    F(GIBLE) \
    F(GABITE) \
    F(GARCHOMP) \
    F(MUNCHLAX) \
    F(RIOLU) \
    F(LUCARIO) \
    F(HIPPOPOTAS) \
    F(HIPPOWDON) \
    F(SKORUPI) \
    F(DRAPION) \
    F(CROAGUNK) \
    F(TOXICROAK) \
    F(CARNIVINE) \
    F(FINNEON) \
    F(LUMINEON) \
    F(MANTYKE) \
    F(SNOVER) \
    F(ABOMASNOW) \
    F(WEAVILE) \
    F(MAGNEZONE) \
    F(LICKILICKY) \
    F(RHYPERIOR) \
    F(TANGROWTH) \
    F(ELECTIVIRE) \
    F(MAGMORTAR) \
    F(TOGEKISS) \
    F(YANMEGA) \
    F(LEAFEON) \
    F(GLACEON) \
    F(GLISCOR) \
    F(MAMOSWINE) \
    F(PORYGON_Z) \
    F(GALLADE) \
    F(PROBOPASS) \
    F(DUSKNOIR) \
    F(FROSLASS) \
    F(ROTOM) \
    F(UXIE) \
    F(MESPRIT) \
    F(AZELF) \
    F(DIALGA) \
    F(PALKIA) \
    F(HEATRAN) \
    F(REGIGIGAS) \
    F(GIRATINA) \
    F(CRESSELIA) \
    F(PHIONE) \
    F(MANAPHY) \
    F(DARKRAI) \
    F(SHAYMIN) \
    F(ARCEUS) \
    F(VICTINI) \
    F(SNIVY) \
    F(SERVINE) \
    F(SERPERIOR) \
    F(TEPIG) \
    F(PIGNITE) \
    F(EMBOAR) \
    F(OSHAWOTT) \
    F(DEWOTT) \
    F(SAMUROTT) \
    F(PATRAT) \
    F(WATCHOG) \
    F(LILLIPUP) \
    F(HERDIER) \
    F(STOUTLAND) \
    F(PURRLOIN) \
    F(LIEPARD) \
    F(PANSAGE) \
    F(SIMISAGE) \
    F(PANSEAR) \
    F(SIMISEAR) \
    F(PANPOUR) \
    F(SIMIPOUR) \
    F(MUNNA) \
    F(MUSHARNA) \
    F(PIDOVE) \
    F(TRANQUILL) \
    F(UNFEZANT) \
    F(BLITZLE) \
    F(ZEBSTRIKA) \
    F(ROGGENROLA) \
    F(BOLDORE) \
    F(GIGALITH) \
    F(WOOBAT) \
    F(SWOOBAT) \
    F(DRILBUR) \
    F(EXCADRILL) \
    F(AUDINO) \
    F(TIMBURR) \
    F(GURDURR) \
    F(CONKELDURR) \
    F(TYMPOLE) \
    F(PALPITOAD) \
    F(SEISMITOAD) \
    F(THROH) \
    F(SAWK) \
    F(SEWADDLE) \
    F(SWADLOON) \
    F(LEAVANNY) \
    F(VENIPEDE) \
    F(WHIRLIPEDE) \
    F(SCOLIPEDE) \
    F(COTTONEE) \
    F(WHIMSICOTT) \
    F(PETILIL) \
    F(LILLIGANT) \
    F(BASCULIN) \
    F(SANDILE) \
    F(KROKOROK) \
    F(KROOKODILE) \
    F(DARUMAKA) \
    F(DARMANITAN) \
    F(MARACTUS) \
    F(DWEBBLE) \
    F(CRUSTLE) \
    F(SCRAGGY) \
    F(SCRAFTY) \
    F(SIGILYPH) \
    F(YAMASK) \
    F(COFAGRIGUS) \
    F(TIRTOUGA) \
    F(CARRACOSTA) \
    F(ARCHEN) \
    F(ARCHEOPS) \
    F(TRUBBISH) \
    F(GARBODOR) \
    F(ZORUA) \
    F(ZOROARK) \
    F(MINCCINO) \
    F(CINCCINO) \
    F(GOTHITA) \
    F(GOTHORITA) \
    F(GOTHITELLE) \
    F(SOLOSIS) \
    F(DUOSION) \
    F(REUNICLUS) \
    F(DUCKLETT) \
    F(SWANNA) \
    F(VANILLITE) \
    F(VANILLISH) \
    F(VANILLUXE) \
    F(DEERLING) \
    F(SAWSBUCK) \
    F(EMOLGA) \
    F(KARRABLAST) \
    F(ESCAVALIER) \
    F(FOONGUS) \
    F(AMOONGUSS) \
    F(FRILLISH) \
    F(JELLICENT) \
    F(ALOMOMOLA) \
    F(JOLTIK) \
    F(GALVANTULA) \
    F(FERROSEED) \
    F(FERROTHORN) \
    F(KLINK) \
    F(KLANG) \
    F(KLINKLANG) \
    F(TYNAMO) \
    F(EELEKTRIK) \
    F(EELEKTROSS) \
    F(ELGYEM) \
    F(BEHEEYEM) \
    F(LITWICK) \
    F(LAMPENT) \
    F(CHANDELURE) \
    F(AXEW) \
    F(FRAXURE) \
    F(HAXORUS) \
    F(CUBCHOO) \
    F(BEARTIC) \
    F(CRYOGONAL) \
    F(SHELMET) \
    F(ACCELGOR) \
    F(STUNFISK) \
    F(MIENFOO) \
    F(MIENSHAO) \
    F(DRUDDIGON) \
    F(GOLETT) \
    F(GOLURK) \
    F(PAWNIARD) \
    F(BISHARP) \
    F(BOUFFALANT) \
    F(RUFFLET) \
    F(BRAVIARY) \
    F(VULLABY) \
    F(MANDIBUZZ) \
    F(HEATMOR) \
    F(DURANT) \
    F(DEINO) \
    F(ZWEILOUS) \
    F(HYDREIGON) \
    F(LARVESTA) \
    F(VOLCARONA) \
    F(COBALION) \
    F(TERRAKION) \
    F(VIRIZION) \
    F(TORNADUS) \
    F(THUNDURUS) \
    F(RESHIRAM) \
    F(ZEKROM) \
    F(LANDORUS) \
    F(KYUREM) \
    F(KELDEO) \
    F(MELOETTA) \
    F(GENESECT) \
    F(CHESPIN) \
    F(QUILLADIN) \
    F(CHESNAUGHT) \
    F(FENNEKIN) \
    F(BRAIXEN) \
    F(DELPHOX) \
    F(FROAKIE) \
    F(FROGADIER) \
    F(GRENINJA) \
    F(BUNNELBY) \
    F(DIGGERSBY) \
    F(FLETCHLING) \
    F(FLETCHINDER) \
    F(TALONFLAME) \
    F(SCATTERBUG) \
    F(SPEWPA) \
    F(VIVILLON) \
    F(LITLEO) \
    F(PYROAR) \
    F(FLABEBE) \
    F(FLOETTE) \
    F(FLORGES) \
    F(SKIDDO) \
    F(GOGOAT) \
    F(PANCHAM) \
    F(PANGORO) \
    F(FURFROU) \
    F(ESPURR) \
    F(MEOWSTIC) \
    F(HONEDGE) \
    F(DOUBLADE) \
    F(AEGISLASH) \
    F(SPRITZEE) \
    F(AROMATISSE) \
    F(SWIRLIX) \
    F(SLURPUFF) \
    F(INKAY) \
    F(MALAMAR) \
    F(BINACLE) \
    F(BARBARACLE) \
    F(SKRELP) \
    F(DRAGALGE) \
    F(CLAUNCHER) \
    F(CLAWITZER) \
    F(HELIOPTILE) \
    F(HELIOLISK) \
    F(TYRUNT) \
    F(TYRANTRUM) \
    F(AMAURA) \
    F(AURORUS) \
    F(SYLVEON) \
    F(HAWLUCHA) \
    F(DEDENNE) \
    F(CARBINK) \
    F(GOOMY) \
    F(SLIGGOO) \
    F(GOODRA) \
    F(KLEFKI) \
    F(PHANTUMP) \
    F(TREVENANT) \
    F(PUMPKABOO) \
    F(GOURGEIST) \
    F(BERGMITE) \
    F(AVALUGG) \
    F(NOIBAT) \
    F(NOIVERN) \
    F(XERNEAS) \
    F(YVELTAL) \
    F(ZYGARDE) \
    F(DIANCIE) \
    F(HOOPA) \
    F(VOLCANION) \
    F(ROWLET) \
    F(DARTRIX) \
    F(DECIDUEYE) \
    F(LITTEN) \
    F(TORRACAT) \
    F(INCINEROAR) \
    F(POPPLIO) \
    F(BRIONNE) \
    F(PRIMARINA) \
    F(PIKIPEK) \
    F(TRUMBEAK) \
    F(TOUCANNON) \
    F(YUNGOOS) \
    F(GUMSHOOS) \
    F(GRUBBIN) \
    F(CHARJABUG) \
    F(VIKAVOLT) \
    F(CRABRAWLER) \
    F(CRABOMINABLE) \
    F(ORICORIO) \
    F(CUTIEFLY) \
    F(RIBOMBEE) \
    F(ROCKRUFF) \
    F(LYCANROC) \
    F(WISHIWASHI) \
    F(MAREANIE) \
    F(TOXAPEX) \
    F(MUDBRAY) \
    F(MUDSDALE) \
    F(DEWPIDER) \
    F(ARAQUANID) \
    F(FOMANTIS) \
    F(LURANTIS) \
    F(MORELULL) \
    F(SHIINOTIC) \
    F(SALANDIT) \
    F(SALAZZLE) \
    F(STUFFUL) \
    F(BEWEAR) \
    F(BOUNSWEET) \
    F(STEENEE) \
    F(TSAREENA) \
    F(COMFEY) \
    F(ORANGURU) \
    F(PASSIMIAN) \
    F(WIMPOD) \
    F(GOLISOPOD) \
    F(SANDYGAST) \
    F(PALOSSAND) \
    F(PYUKUMUKU) \
    F(TYPE_NULL) \
    F(SILVALLY) \
    F(MINIOR) \
    F(KOMALA) \
    F(TURTONATOR) \
    F(TOGEDEMARU) \
    F(MIMIKYU) \
    F(BRUXISH) \
    F(DRAMPA) \
    F(DHELMISE) \
    F(JANGMO_O) \
    F(HAKAMO_O) \
    F(KOMMO_O) \
    F(TAPU_KOKO) \
    F(TAPU_LELE) \
    F(TAPU_BULU) \
    F(TAPU_FINI) \
    F(COSMOG) \
    F(COSMOEM) \
    F(SOLGALEO) \
    F(LUNALA) \
    F(NIHILEGO) \
    F(BUZZWOLE) \
    F(PHEROMOSA) \
    F(XURKITREE) \
    F(CELESTEELA) \
    F(KARTANA) \
    F(GUZZLORD) \
    F(NECROZMA) \
    F(MAGEARNA) \
    F(MARSHADOW) \
    F(POIPOLE) \
    F(NAGANADEL) \
    F(STAKATAKA) \
    F(BLACEPHALON) \
    F(ZERAORA) \
    F(MELTAN) \
    F(MELMETAL) \
    F(GROOKEY) \
    F(THWACKEY) \
    F(RILLABOOM) \
    F(SCORBUNNY) \
    F(RABOOT) \
    F(CINDERACE) \
    F(SOBBLE) \
    F(DRIZZILE) \
    F(INTELEON) \
    F(SKWOVET) \
    F(GREEDENT) \
    F(ROOKIDEE) \
    F(CORVISQUIRE) \
    F(CORVIKNIGHT) \
    F(BLIPBUG) \
    F(DOTTLER) \
    F(ORBEETLE) \
    F(NICKIT) \
    F(THIEVUL) \
    F(GOSSIFLEUR) \
    F(ELDEGOSS) \
    F(WOOLOO) \
    F(DUBWOOL) \
    F(CHEWTLE) \
    F(DREDNAW) \
    F(YAMPER) \
    F(BOLTUND) \
    F(ROLYCOLY) \
    F(CARKOL) \
    F(COALOSSAL) \
    F(APPLIN) \
    F(FLAPPLE) \
    F(APPLETUN) \
    F(SILICOBRA) \
    F(SANDACONDA) \
    F(CRAMORANT) \
    F(ARROKUDA) \
    F(BARRASKEWDA) \
    F(TOXEL) \
    F(TOXTRICITY) \
    F(SIZZLIPEDE) \
    F(CENTISKORCH) \
    F(CLOBBOPUS) \
    F(GRAPPLOCT) \
    F(SINISTEA) \
    F(POLTEAGEIST) \
    F(HATENNA) \
    F(HATTREM) \
    F(HATTERENE) \
    F(IMPIDIMP) \
    F(MORGREM) \
    F(GRIMMSNARL) \
    F(OBSTAGOON) \
    F(PERRSERKER) \
    F(CURSOLA) \
    F(SIRFETCHD) \
    F(MR_RIME) \
    F(RUNERIGUS) \
    F(MILCERY) \
    F(ALCREMIE) \
    F(FALINKS) \
    F(PINCURCHIN) \
    F(SNOM) \
    F(FROSMOTH) \
    F(STONJOURNER) \
    F(EISCUE) \
    F(INDEEDEE) \
    F(MORPEKO) \
    F(CUFANT) \
    F(COPPERAJAH) \
    F(DRACOZOLT) \
    F(ARCTOZOLT) \
    F(DRACOVISH) \
    F(ARCTOVISH) \
    F(DURALUDON) \
    F(DREEPY) \
    F(DRAKLOAK) \
    F(DRAGAPULT) \
    F(ZACIAN) \
    F(ZAMAZENTA) \
    F(ETERNATUS) \
    F(KUBFU) \
    F(URSHIFU) \
    F(ZARUDE) \
    F(REGIELEKI) \
    F(REGIDRAGO) \
    F(GLASTRIER) \
    F(SPECTRIER) \
    F(CALYREX) \
    F(WYRDEER) \
    F(KLEAVOR) \
    F(URSALUNA) \
    F(BASCULEGION) \
    F(SNEASLER) \
    F(OVERQWIL) \
    F(ENAMORUS) \
    F(SPRIGATITO) \
    F(FLORAGATO) \
    F(MEOWSCARADA) \
    F(FUECOCO) \
    F(CROCALOR) \
    F(SKELEDIRGE) \
    F(QUAXLY) \
    F(QUAXWELL) \
    F(QUAQUAVAL) \
    F(LECHONK) \
    F(OINKOLOGNE) \
    F(TAROUNTULA) \
    F(SPIDOPS) \
    F(NYMBLE) \
    F(LOKIX) \
    F(PAWMI) \
    F(PAWMO) \
    F(PAWMOT) \
    F(TANDEMAUS) \
    F(MAUSHOLD) \
    F(FIDOUGH) \
    F(DACHSBUN) \
    F(SMOLIV) \
    F(DOLLIV) \
    F(ARBOLIVA) \
    F(SQUAWKABILLY) \
    F(NACLI) \
    F(NACLSTACK) \
    F(GARGANACL) \
    F(CHARCADET) \
    F(ARMAROUGE) \
    F(CERULEDGE) \
    F(TADBULB) \
    F(BELLIBOLT) \
    F(WATTREL) \
    F(KILOWATTREL) \
    F(MASCHIFF) \
    F(MABOSSTIFF) \
    F(SHROODLE) \
    F(GRAFAIAI) \
    F(BRAMBLIN) \
    F(BRAMBLEGHAST) \
    F(TOEDSCOOL) \
    F(TOEDSCRUEL) \
    F(KLAWF) \
    F(CAPSAKID) \
    F(SCOVILLAIN) \
    F(RELLOR) \
    F(RABSCA) \
    F(FLITTLE) \
    F(ESPATHRA) \
    F(TINKATINK) \
    F(TINKATUFF) \
    F(TINKATON) \
    F(WIGLETT) \
    F(WUGTRIO) \
    F(BOMBIRDIER) \
    F(FINIZEN) \
    F(PALAFIN) \
    F(VAROOM) \
    F(REVAVROOM) \
    F(CYCLIZAR) \
    F(ORTHWORM) \
    F(GLIMMET) \
    F(GLIMMORA) \
    F(GREAVARD) \
    F(HOUNDSTONE) \
    F(FLAMIGO) \
    F(CETODDLE) \
    F(CETITAN) \
    F(VELUZA) \
    F(DONDOZO) \
    F(TATSUGIRI) \
    F(ANNIHILAPE) \
    F(CLODSIRE) \
    F(FARIGIRAF) \
    F(DUDUNSPARCE) \
    F(KINGAMBIT) \
    F(GREAT_TUSK) \
    F(SCREAM_TAIL) \
    F(BRUTE_BONNET) \
    F(FLUTTER_MANE) \
    F(SLITHER_WING) \
    F(SANDY_SHOCKS) \
    F(IRON_TREADS) \
    F(IRON_BUNDLE) \
    F(IRON_HANDS) \
    F(IRON_JUGULIS) \
    F(IRON_MOTH) \
    F(IRON_THORNS) \
    F(FRIGIBAX) \
    F(ARCTIBAX) \
    F(BAXCALIBUR) \
    F(GIMMIGHOUL) \
    F(GHOLDENGO) \
    F(WO_CHIEN) \
    F(CHIEN_PAO) \
    F(TING_LU) \
    F(CHI_YU) \
    F(ROARING_MOON) \
    F(IRON_VALIANT) \
    F(KORAIDON) \
    F(MIRAIDON) \
    F(WALKING_WAKE) \
    F(IRON_LEAVES) \
    F(DIPPLIN) \
    F(POLTCHAGEIST) \
    F(SINISTCHA) \
    F(OKIDOGI) \
    F(MUNKIDORI) \
    F(FEZANDIPITI) \
    F(OGERPON) \
    F(ARCHALUDON) \
    F(HYDRAPPLE) \
    F(GOUGING_FIRE) \
    F(RAGING_BOLT) \
    F(IRON_BOULDER) \
    F(IRON_CROWN) \
    F(TERAPAGOS) \
    F(PECHARUNT)

// National Pokédex order
// These constants are NOT disabled by P_GEN_X_POKEMON to keep pokedex_orders.h clean.
enum NationalDexOrder
{
    #define NATIONAL_DEX_ENUM(name) NATIONAL_DEX_ ##name,
    FOREACH_SPECIES_IN_NATIONAL_DEX(NATIONAL_DEX_ENUM)
    #undef NATIONAL_DEX_ENUM
    NATIONAL_DEX_END
};

#if P_NEW_EVOS_IN_REGIONAL_DEX
#define KANTO_DEX_IF(config, ...) CAT(KANTO_DEX_IF_, config)(__VA_ARGS__)
#define KANTO_DEX_IF_0(...)
#define KANTO_DEX_IF_1(...) __VA_ARGS__
#else
#define KANTO_DEX_IF(config, ...)
#endif

#define FOREACH_SPECIES_IN_KANTO_DEX_ORDER(F) \
    F(BULBASAUR) \
    F(IVYSAUR) \
    F(VENUSAUR) \
    F(CHARMANDER) \
    F(CHARMELEON) \
    F(CHARIZARD) \
    F(SQUIRTLE) \
    F(WARTORTLE) \
    F(BLASTOISE) \
    F(CATERPIE) \
    F(METAPOD) \
    F(BUTTERFREE) \
    F(WEEDLE) \
    F(KAKUNA) \
    F(BEEDRILL) \
    F(PIDGEY) \
    F(PIDGEOTTO) \
    F(PIDGEOT) \
    F(RATTATA) \
    F(RATICATE) \
    F(SPEAROW) \
    F(FEAROW) \
    F(EKANS) \
    F(ARBOK) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(PICHU)) \
    F(PIKACHU) \
    F(RAICHU) \
    F(SANDSHREW) \
    F(SANDSLASH) \
    F(NIDORAN_F) \
    F(NIDORINA) \
    F(NIDOQUEEN) \
    F(NIDORAN_M) \
    F(NIDORINO) \
    F(NIDOKING) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(CLEFFA)) \
    F(CLEFAIRY) \
    F(CLEFABLE) \
    F(VULPIX) \
    F(NINETALES) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(IGGLYBUFF)) \
    F(JIGGLYPUFF) \
    F(WIGGLYTUFF) \
    F(ZUBAT) \
    F(GOLBAT) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(CROBAT)) \
    F(ODDISH) \
    F(GLOOM) \
    F(VILEPLUME) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(BELLOSSOM)) \
    F(PARAS) \
    F(PARASECT) \
    F(VENONAT) \
    F(VENOMOTH) \
    F(DIGLETT) \
    F(DUGTRIO) \
    F(MEOWTH) \
    F(PERSIAN) \
    KANTO_DEX_IF(P_GALARIAN_FORMS, F(PERRSERKER)) \
    F(PSYDUCK) \
    F(GOLDUCK) \
    F(MANKEY) \
    F(PRIMEAPE) \
    KANTO_DEX_IF(P_GEN_9_CROSS_EVOS, F(ANNIHILAPE)) \
    F(GROWLITHE) \
    F(ARCANINE) \
    F(POLIWAG) \
    F(POLIWHIRL) \
    F(POLIWRATH) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(POLITOED)) \
    F(ABRA) \
    F(KADABRA) \
    F(ALAKAZAM) \
    F(MACHOP) \
    F(MACHOKE) \
    F(MACHAMP) \
    F(BELLSPROUT) \
    F(WEEPINBELL) \
    F(VICTREEBEL) \
    F(TENTACOOL) \
    F(TENTACRUEL) \
    F(GEODUDE) \
    F(GRAVELER) \
    F(GOLEM) \
    F(PONYTA) \
    F(RAPIDASH) \
    F(SLOWPOKE) \
    F(SLOWBRO) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SLOWKING)) \
    F(MAGNEMITE) \
    F(MAGNETON) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGNEZONE)) \
    F(FARFETCHD) \
    KANTO_DEX_IF(P_GALARIAN_FORMS, F(SIRFETCHD)) \
    F(DODUO) \
    F(DODRIO) \
    F(SEEL) \
    F(DEWGONG) \
    F(GRIMER) \
    F(MUK) \
    F(SHELLDER) \
    F(CLOYSTER) \
    F(GASTLY) \
    F(HAUNTER) \
    F(GENGAR) \
    F(ONIX) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(STEELIX)) \
    F(DROWZEE) \
    F(HYPNO) \
    F(KRABBY) \
    F(KINGLER) \
    F(VOLTORB) \
    F(ELECTRODE) \
    F(EXEGGCUTE) \
    F(EXEGGUTOR) \
    F(CUBONE) \
    F(MAROWAK) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(TYROGUE)) \
    F(HITMONLEE) \
    F(HITMONCHAN) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(HITMONTOP)) \
    F(LICKITUNG) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(LICKILICKY)) \
    F(KOFFING) \
    F(WEEZING) \
    F(RHYHORN) \
    F(RHYDON) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(RHYPERIOR)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(HAPPINY)) \
    F(CHANSEY) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(BLISSEY)) \
    F(TANGELA) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(TANGROWTH)) \
    F(KANGASKHAN) \
    F(HORSEA) \
    F(SEADRA) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(KINGDRA)) \
    F(GOLDEEN) \
    F(SEAKING) \
    F(STARYU) \
    F(STARMIE) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MIME_JR)) \
    F(MR_MIME) \
    KANTO_DEX_IF(P_GALARIAN_FORMS, F(MR_RIME)) \
    F(SCYTHER) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SCIZOR)) \
    KANTO_DEX_IF(P_GEN_8_CROSS_EVOS, F(KLEAVOR)) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SMOOCHUM)) \
    F(JYNX) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(ELEKID)) \
    F(ELECTABUZZ) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(ELECTIVIRE)) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(MAGBY)) \
    F(MAGMAR) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGMORTAR)) \
    F(PINSIR) \
    F(TAUROS) \
    F(MAGIKARP) \
    F(GYARADOS) \
    F(LAPRAS) \
    F(DITTO) \
    F(EEVEE) \
    F(VAPOREON) \
    F(JOLTEON) \
    F(FLAREON) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(ESPEON)) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(UMBREON)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(LEAFEON)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(GLACEON)) \
    KANTO_DEX_IF(P_GEN_6_CROSS_EVOS, F(SYLVEON)) \
    F(PORYGON) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(PORYGON2)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(PORYGON_Z)) \
    F(OMANYTE) \
    F(OMASTAR) \
    F(KABUTO) \
    F(KABUTOPS) \
    F(AERODACTYL) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MUNCHLAX)) \
    F(SNORLAX) \
    F(ARTICUNO) \
    F(ZAPDOS) \
    F(MOLTRES) \
    F(DRATINI) \
    F(DRAGONAIR) \
    F(DRAGONITE) \
    F(MEWTWO) \
    F(MEW)

// Kanto Pokedex order
enum KantoDexOrder
{
    KANTO_DEX_NONE,
    #define KANTO_DEX_ENUM(name) KANTO_DEX_ ##name,
    FOREACH_SPECIES_IN_KANTO_DEX_ORDER(KANTO_DEX_ENUM)
    #undef KANTO_DEX_ENUM
    KANTO_DEX_END
};


#if P_NEW_EVOS_IN_REGIONAL_DEX
#define HOENN_DEX_IF(config, ...) CAT(HOENN_DEX_IF_, config)(__VA_ARGS__)
#define HOENN_DEX_IF_0(...)
#define HOENN_DEX_IF_1(...) __VA_ARGS__
#else
#define HOENN_DEX_IF(config, ...)
#endif

#define FOREACH_SPECIES_IN_HOENN_DEX_ORDER(F) \
    F(TREECKO) \
    F(GROVYLE) \
    F(SCEPTILE) \
    F(TORCHIC) \
    F(COMBUSKEN) \
    F(BLAZIKEN) \
    F(MUDKIP) \
    F(MARSHTOMP) \
    F(SWAMPERT) \
    F(POOCHYENA) \
    F(MIGHTYENA) \
    F(ZIGZAGOON) \
    F(LINOONE) \
    HOENN_DEX_IF(P_GALARIAN_FORMS, F(OBSTAGOON)) \
    F(WURMPLE) \
    F(SILCOON) \
    F(BEAUTIFLY) \
    F(CASCOON) \
    F(DUSTOX) \
    F(LOTAD) \
    F(LOMBRE) \
    F(LUDICOLO) \
    F(SEEDOT) \
    F(NUZLEAF) \
    F(SHIFTRY) \
    F(TAILLOW) \
    F(SWELLOW) \
    F(WINGULL) \
    F(PELIPPER) \
    F(RALTS) \
    F(KIRLIA) \
    F(GARDEVOIR) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(GALLADE)) \
    F(SURSKIT) \
    F(MASQUERAIN) \
    F(SHROOMISH) \
    F(BRELOOM) \
    F(SLAKOTH) \
    F(VIGOROTH) \
    F(SLAKING) \
    F(ABRA) \
    F(KADABRA) \
    F(ALAKAZAM) \
    F(NINCADA) \
    F(NINJASK) \
    F(SHEDINJA) \
    F(WHISMUR) \
    F(LOUDRED) \
    F(EXPLOUD) \
    F(MAKUHITA) \
    F(HARIYAMA) \
    F(GOLDEEN) \
    F(SEAKING) \
    F(MAGIKARP) \
    F(GYARADOS) \
    F(AZURILL) \
    F(MARILL) \
    F(AZUMARILL) \
    F(GEODUDE) \
    F(GRAVELER) \
    F(GOLEM) \
    F(NOSEPASS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(PROBOPASS)) \
    F(SKITTY) \
    F(DELCATTY) \
    F(ZUBAT) \
    F(GOLBAT) \
    F(CROBAT) \
    F(TENTACOOL) \
    F(TENTACRUEL) \
    F(SABLEYE) \
    F(MAWILE) \
    F(ARON) \
    F(LAIRON) \
    F(AGGRON) \
    F(MACHOP) \
    F(MACHOKE) \
    F(MACHAMP) \
    F(MEDITITE) \
    F(MEDICHAM) \
    F(ELECTRIKE) \
    F(MANECTRIC) \
    F(PLUSLE) \
    F(MINUN) \
    F(MAGNEMITE) \
    F(MAGNETON) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGNEZONE)) \
    F(VOLTORB) \
    F(ELECTRODE) \
    F(VOLBEAT) \
    F(ILLUMISE) \
    F(ODDISH) \
    F(GLOOM) \
    F(VILEPLUME) \
    F(BELLOSSOM) \
    F(DODUO) \
    F(DODRIO) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(BUDEW)) \
    F(ROSELIA) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(ROSERADE)) \
    F(GULPIN) \
    F(SWALOT) \
    F(CARVANHA) \
    F(SHARPEDO) \
    F(WAILMER) \
    F(WAILORD) \
    F(NUMEL) \
    F(CAMERUPT) \
    F(SLUGMA) \
    F(MAGCARGO) \
    F(TORKOAL) \
    F(GRIMER) \
    F(MUK) \
    F(KOFFING) \
    F(WEEZING) \
    F(SPOINK) \
    F(GRUMPIG) \
    F(SANDSHREW) \
    F(SANDSLASH) \
    F(SPINDA) \
    F(SKARMORY) \
    F(TRAPINCH) \
    F(VIBRAVA) \
    F(FLYGON) \
    F(CACNEA) \
    F(CACTURNE) \
    F(SWABLU) \
    F(ALTARIA) \
    F(ZANGOOSE) \
    F(SEVIPER) \
    F(LUNATONE) \
    F(SOLROCK) \
    F(BARBOACH) \
    F(WHISCASH) \
    F(CORPHISH) \
    F(CRAWDAUNT) \
    F(BALTOY) \
    F(CLAYDOL) \
    F(LILEEP) \
    F(CRADILY) \
    F(ANORITH) \
    F(ARMALDO) \
    F(IGGLYBUFF) \
    F(JIGGLYPUFF) \
    F(WIGGLYTUFF) \
    F(FEEBAS) \
    F(MILOTIC) \
    F(CASTFORM) \
    F(STARYU) \
    F(STARMIE) \
    F(KECLEON) \
    F(SHUPPET) \
    F(BANETTE) \
    F(DUSKULL) \
    F(DUSCLOPS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(DUSKNOIR)) \
    F(TROPIUS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(CHINGLING)) \
    F(CHIMECHO) \
    F(ABSOL) \
    F(VULPIX) \
    F(NINETALES) \
    F(PICHU) \
    F(PIKACHU) \
    F(RAICHU) \
    F(PSYDUCK) \
    F(GOLDUCK) \
    F(WYNAUT) \
    F(WOBBUFFET) \
    F(NATU) \
    F(XATU) \
    F(GIRAFARIG) \
    HOENN_DEX_IF(P_GEN_9_CROSS_EVOS, F(FARIGIRAF)) \
    F(PHANPY) \
    F(DONPHAN) \
    F(PINSIR) \
    F(HERACROSS) \
    F(RHYHORN) \
    F(RHYDON) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(RHYPERIOR)) \
    F(SNORUNT) \
    F(GLALIE) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(FROSLASS)) \
    F(SPHEAL) \
    F(SEALEO) \
    F(WALREIN) \
    F(CLAMPERL) \
    F(HUNTAIL) \
    F(GOREBYSS) \
    F(RELICANTH) \
    F(CORSOLA) \
    HOENN_DEX_IF(P_GALARIAN_FORMS, F(CURSOLA)) \
    F(CHINCHOU) \
    F(LANTURN) \
    F(LUVDISC) \
    F(HORSEA) \
    F(SEADRA) \
    F(KINGDRA) \
    F(BAGON) \
    F(SHELGON) \
    F(SALAMENCE) \
    F(BELDUM) \
    F(METANG) \
    F(METAGROSS) \
    F(REGIROCK) \
    F(REGICE) \
    F(REGISTEEL) \
    F(LATIAS) \
    F(LATIOS) \
    F(KYOGRE) \
    F(GROUDON) \
    F(RAYQUAZA) \
    F(JIRACHI) \
    F(DEOXYS)

// Hoenn Pokédex order
enum HoennDexOrder
{
    HOENN_DEX_NONE,
    #define HOENN_DEX_ENUM(name) HOENN_DEX_ ##name,
    FOREACH_SPECIES_IN_HOENN_DEX_ORDER(HOENN_DEX_ENUM)
    #undef HOENN_DEX_ENUM
    HOENN_DEX_END,
};


#define KANTO_DEX_START KANTO_DEX_BULBASAUR
#define HOENN_DEX_START HOENN_DEX_TREECKO

#define KANTO_DEX_COUNT KANTO_DEX_MEW
#define HOENN_DEX_COUNT (HOENN_DEX_DEOXYS + 1)

#define NATIONAL_DEX_START NATIONAL_DEX_BULBASAUR
#if P_GEN_9_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_PECHARUNT
#elif P_GEN_9_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_HYDRAPPLE
#elif P_PALDEAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_CLODSIRE

#elif P_GEN_8_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ENAMORUS
#elif P_HISUIAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_OVERQWIL
#elif P_GEN_8_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_URSALUNA
#elif P_GALARIAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_RUNERIGUS

#elif P_GEN_7_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_MELMETAL

#elif P_GEN_6_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_VOLCANION
#elif P_GEN_6_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_SYLVEON

#elif P_GEN_5_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_GENESECT

#elif P_GEN_4_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ARCEUS
#elif P_GEN_4_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_FROSLASS

#else
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_DEOXYS
#endif

#define POKEMON_SLOTS_NUMBER (NATIONAL_DEX_COUNT + 1)


#define DECAGRAMS_IN_POUND             453592
#define CM_PER_INCH                    2.54
#define CM_PER_INCH_FACTOR             (CM_PER_INCH * 100)
#define INCHES_IN_FOOT                 12
#define INCHES_IN_ONE_AND_HALF_FOOT    (INCHES_IN_FOOT * 1.5)
#define INCHES_IN_FOOT_FACTOR          (INCHES_IN_FOOT * 10)

#define WEIGHT_HEIGHT_STR_LEN          16
#define WEIGHT_HEIGHT_STR_MEM          (WEIGHT_HEIGHT_STR_LEN * sizeof(u8))

#define DEX_HEADER_X                   96
#define DEX_Y_TOP                      57
#define DEX_Y_BOTTOM                   73
#define DEX_MEASUREMENT_X              129

#define DEX_HGSS_HEADER_X_PADDING      59
#define DEX_HGSS_Y_TOP_PADDING         7
#define DEX_HGSS_Y_BOTTOM_PADDING      4
#define DEX_HGSS_MEASUREMENT_X_PADDING 51

enum
{
    DEX_MODE_KANTO,
    DEX_MODE_NATIONAL
};

enum
{
    FLAG_GET_SEEN,
    FLAG_GET_CAUGHT,
    FLAG_SET_SEEN,
    FLAG_SET_CAUGHT
};

#endif // GUARD_CONSTANTS_POKEDEX_H
