#ifndef GUARD_SCRIPT_MENU_CONSTANTS_H
#define GUARD_SCRIPT_MENU_CONSTANTS_H

#define MULTICHOICE(name) {.list = name, .count = ARRAY_COUNT(name)}

#define MAX_MULTICHOICE_WIDTH 28

#define MULTI_B_PRESSED 127
#define SCR_MENU_UNSET  255


// Multichoice Ids
enum MultichoiceID
{
    MULTI_YESNO,
    MULTI_EEVEELUTIONS,
    MULTI_TRAINER_CARD_ICON_TINT,
    MULTI_HOF_QUIT,
    MULTI_EGGS_QUIT,
    MULTI_VICTORIES_QUIT,
    MULTI_HOF_EGGS_QUIT,
    MULTI_HOF_VICTORIES_QUIT,
    MULTI_EGGS_VICTORIES_QUIT,
    MULTI_HOF_EGGS_VICTORIES_QUIT,
    MULTI_BIKE_SHOP,
    MULTI_GAME_CORNER_POKEMON_PRIZES,
    MULTI_TRAINER_SCHOOL_WHITEBOARD,
    MULTI_YES_NO_INFO,
    MULTI_SINGLE_DOUBLE_MULTI_INFO_EXIT,
    MULTI_CHALLENGEINFO,
    MULTI_ROOFTOP_B1F,
    MULTI_HELIX,
    MULTI_DOME,
    MULTI_AMBER,
    MULTI_HELIX_AMBER,
    MULTI_DOME_AMBER,
    MULTI_CELADON_VENDING_MACHINE,
    MULTI_GAME_CORNER_COIN_PURCHASE_COUNTER,
    MULTI_GAME_CORNER_TMPRIZES,
    MULTI_DEPT_STORE_ELEVATOR,
    MULTI_THIRSTY_GIRL_FRESH_WATER,
    MULTI_THIRSTY_GIRL_SODA_POP,
    MULTI_THIRSTY_GIRL_FRESH_WATER_SODA_POP,
    MULTI_THIRSTY_GIRL_LEMONADE,
    MULTI_THIRSTY_GIRL_FRESH_WATER_LEMONADE,
    MULTI_THIRSTY_GIRL_SODA_POP_LEMONADE,
    MULTI_THIRSTY_GIRL_FRESH_WATER_SODA_POP_LEMONADE,
    MULTI_TRADE_CENTER_COLOSSEUM,
    MULTI_GAME_CORNER_BATTLE_ITEM_PRIZES,
    MULTI_ROCKET_HIDEOUT_ELEVATOR,
    MULTI_LINKED_DIRECT_UNION,
    MULTI_ISLAND_23,
    MULTI_ISLAND_13,
    MULTI_ISLAND_12,
    MULTI_TRADE_COLOSSEUM_CRUSH,
    MULTI_POKEJUMP_DODRIO,
    MULTI_TRADE_COLOSSEUM_2,
    MULTI_MUSHROOMS,
    MULTI_SEVII_NAVEL,
    MULTI_SEVII_BIRTH,
    MULTI_SEVII_NAVEL_BIRTH,
    MULTI_SEAGALLOP_123,
    MULTI_SEAGALLOP_V23,
    MULTI_SEAGALLOP_V13,
    MULTI_SEAGALLOP_V12,
    MULTI_SEAGALLOP_VERMILION,
    MULTI_JOIN_OR_LEAD,
    MULTI_TRAINER_TOWER_MODE,
    MULTI_FRONTIER_RULES,
    MULTI_FRONTIER_PASS_INFO,
    MULTI_FRONTIER_GAMBLER_BET,
    MULTI_LEVEL_MODE,
    MULTI_BATTLE_FACTORY_RULES,
    MULTI_GO_ON_RECORD_REST_RETIRE,
    MULTI_GO_ON_REST_RETIRE,
    MULTI_GO_ON_RECORD_RETIRE,
    MULTI_GO_ON_RETIRE,
    MULTI_BATTLE_ARENA_RULES,
    MULTI_BATTLE_DOME_RULES,
    MULTI_TOURNEY_WITH_RECORD,
    MULTI_TOURNEY_NO_RECORD,
    MULTI_BATTLE_PALACE_RULES,
    MULTI_BATTLE_PYRAMID_RULES,
    MULTI_BATTLE_PIKE_RULES,
    MULTI_FRONTIER_ITEM_CHOOSE,
    MULTI_BATTLE_TOWER_RULES,
    MULTI_BATTLE_TOWER_FEELINGS,
    MULTI_LINK_LEADER,
    MULTI_SATISFACTION,
    MULTI_JOURNAL,
    MULTI_TEST_NPC_CHOICES,
    MULTI_TEST_NPC_PREVIEW_MODES,
    MULTI_WORKBENCH,
    MULTI_CRAFT_QUANTITY,
    MULTI_WORKBENCH_MENU,
    MULTI_WORKBENCH_UPGRADE_SOURCE,
    MULTI_MEDICINE_CRAFTING,
    MULTI_FUJI_ROOM_MONS,
    MULTI_COURIER_MENU,
    MULTI_COURIER_ROOM_RANGES_WITH_UPGRADE,
    MULTI_COURIER_ROOM_RANGES_NO_UPGRADE,
    MULTI_COURIER_ROOMS_1_4,
    MULTI_COURIER_ROOMS_5_8,
    MULTI_COURIER_ROOMS_9_10,
    MULTI_RESEARCH_MAIN,
    MULTI_RESEARCH_SHOP,
    MULTI_RESEARCH_ITEMS,
    MULTI_RESEARCH_POKEMON,
    MULTI_RESERVE_CONTEST_CATEGORY,
    MULTI_RESERVE_CONTEST_LOG_DECISION,
    MULTI_RESERVE_CONTEST_KEEP_SPECIMEN,

    MULTI_NONE = 255,
};

// Dynamic Multichoice Callbacks

#define DYN_MULTICHOICE_CB_DEBUG      0
#define DYN_MULTICHOICE_CB_SHOW_ITEM  1
#define DYN_MULTICHOICE_CB_NONE       255

#endif //GUARD_SCRIPT_MENU_CONSTANTS_H
