#ifndef GUARD_CONSTANTS_WEATHER_H
#define GUARD_CONSTANTS_WEATHER_H

enum Weather
{
    WEATHER_NONE,
    WEATHER_SUNNY_CLOUDS,
    WEATHER_SUNNY,
    WEATHER_RAIN,
    WEATHER_SNOW,
    WEATHER_RAIN_THUNDERSTORM,
    WEATHER_FOG_HORIZONTAL,
    WEATHER_VOLCANIC_ASH,
    WEATHER_SANDSTORM,
    WEATHER_FOG_DIAGONAL,
    WEATHER_UNDERWATER,
    WEATHER_SHADE,
    WEATHER_DROUGHT,
    WEATHER_DOWNPOUR,
    WEATHER_UNDERWATER_BUBBLES,
    WEATHER_ABNORMAL,
    WEATHER_ROUTE119_CYCLE = 20,  // unused
    WEATHER_ROUTE123_CYCLE,       // unused
    WEATHER_FOG,                  // Aggregate of WEATHER_FOG_HORIZONTAL and WEATHER_FOG_DIAGONAL
    WEATHER_ELECTRIC_FLOOR,
    WEATHER_POISON_FOG,
    WEATHER_COUNT,
};

// These are used in maps' coord_weather_event entries.
// They are not a one-to-one mapping with the engine's
// internal weather constants above.
#define COORD_EVENT_WEATHER_SUNNY_CLOUDS        1
#define COORD_EVENT_WEATHER_SUNNY               2
#define COORD_EVENT_WEATHER_RAIN                3
#define COORD_EVENT_WEATHER_SNOW                4
#define COORD_EVENT_WEATHER_RAIN_THUNDERSTORM   5
#define COORD_EVENT_WEATHER_FOG_HORIZONTAL      6
#define COORD_EVENT_WEATHER_FOG_DIAGONAL        7
#define COORD_EVENT_WEATHER_VOLCANIC_ASH        8
#define COORD_EVENT_WEATHER_SANDSTORM           9
#define COORD_EVENT_WEATHER_SHADE               10
#define COORD_EVENT_WEATHER_DROUGHT             11
#define COORD_EVENT_WEATHER_ELECTRIC_FLOOR      12
#define COORD_EVENT_WEATHER_POISON_FOG          13
#define COORD_EVENT_WEATHER_ROUTE119_CYCLE      20
#define COORD_EVENT_WEATHER_ROUTE123_CYCLE      21

#endif  // GUARD_CONSTANTS_WEATHER_H
