SSAnne_1F_Room6_Text_TakeAShortRest::
    .string "You look tired. Would you like to\n"
    .string "take a short rest?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
    .string "I'm glad to see that everyone is\n"
    .string "looking refreshed and chipper.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .string "Oh, I'm sorry for fussing over you.\n"
    .string "You look like my little brother…$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .string "Oh, I'm sorry for fussing over you.\n"
    .string "You look like my little sister…$"

SSAnne_1F_Room6_Text_ChooseGrowlithe::
    .string "Do you want to choose the fire\n"
    .string "POKéMON GROWLITHE?$"

SSAnne_1F_Room6_Text_ObtainedGrowlithe::
    .string "{PLAYER} obtained GROWLITHE!$"

SSAnne_1F_Room6_Text_ChooseNidoranM::
    .string "Do you want to choose the poison pin\n"
    .string "POKéMON NIDORAN♂?$"

SSAnne_1F_Room6_Text_ObtainedNidoranM::
    .string "{PLAYER} obtained NIDORAN♂!$"

SSAnne_1F_Room6_Text_ChooseExeggcute::
    .string "Do you want to choose the egg\n"
    .string "POKéMON EXEGGCUTE?$"

SSAnne_1F_Room6_Text_ObtainedExeggcute::
    .string "{PLAYER} obtained EXEGGCUTE!$"

SSAnne_1F_Room6_Text_GrowlitheFriendly::
    .string "GROWLITHE looks very happy!$"

SSAnne_1F_Room6_Text_NidoranMFriendly::
    .string "NIDORAN♂ looks friendly!$"

SSAnne_1F_Room6_Text_ExeggcuteFriendly::
    .string "EXEGGCUTE is content!$"

SSAnne_1F_Room6_Text_ScientistIntro::
    .string "I'm a researcher from Silph Co.\p"
    .string "We're prototyping new Poké Ball tech.\p"
    .string "If you bring me Apricorns and a\n"
    .string "Conversion Kit, I can craft them.\p"
    .string "Would you like me to craft a Protoball?$"

SSAnne_1F_Room6_Text_ScientistDecline::
    .string "Come back if you need me to craft\n"
    .string "any Protoballs.$"

