PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!$"

PalletTown_PlayersHouse_2F_Text_AgathaTest1::
    .string "Agatha: Oak! You old fool!\n"
    .string "You think you can hide in Pallet?$"

PalletTown_PlayersHouse_2F_Text_OakTest1::
    .string "Oak: Ah, Agatha...\n"
    .string "It's good to see you, too.$"


