gText_PkmnTransferredSomeonesPC::
    .string "{STR_VAR_2} was sent to\n"
    .string "FUJI'S LAB.\p"
    .string "It was placed in \n"
    .string "ROOM {STR_VAR_1}.$"

gText_PkmnTransferredBillsPC::
    .string "{STR_VAR_2} was sent to\n"
    .string "FUJI'S LAB.\p"
    .string "It was placed in \n"
    .string "ROOM {STR_VAR_1}.$"

gText_PkmnTransferredSomeonesPCBoxFull::
    .string "ROOM {STR_VAR_3} in\n"
    .string "FUJI'S LAB was full.\p"
    .string "{STR_VAR_2} was transferred to\n"
    .string "ROOM {STR_VAR_1}.$"

gText_PkmnTransferredBillsPCBoxFull::
    .string "ROOM {STR_VAR_3} in\n"
    .string "FUJI'S LAB was full.\p"
    .string "{STR_VAR_2} was transferred to\n"
    .string "ROOM {STR_VAR_1}.$"

gText_PkmnSentToPCAfterCatch::
	.string "{STR_VAR_2} was sent to\n"
	.string "{B_PC_CREATOR_NAME} PC.\p"
	.string "It was placed in \n"
	.string "BOX “{STR_VAR_1}”.$"

gText_PkmnSentToFujiAfterCatch::
	.string "{STR_VAR_2} was sent to\n"
	.string "FUJI'S LAB.\p"
	.string "It was placed in \n"
	.string "ROOM {STR_VAR_1}.$"

Text_PlayerObtainedTheMon::
    .string "{PLAYER} obtained\n"
    .string "the {STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "There's no more room for POKéMON!\p"
    .string "The POKéMON BOXES are full and\n"
    .string "can't accept any more!$"
