VictoryRoad_2F_EventScript_DoubleEdgeTutor::
	lock
	faceplayer
	move_tutor MOVE_DOUBLE_EDGE, Text_DoubleEdgeTeach, Text_DoubleEdgeWhichMon, EventScript_DoubleEdgeDeclined, EventScript_DoubleEdgeTaught, FLAG_0x2C0
	end

EventScript_DoubleEdgeDeclined::
	msgbox Text_DoubleEdgeDeclined
	release
	end

EventScript_DoubleEdgeTaught::
	msgbox Text_DoubleEdgeTaught
	release
	end

EventScript_ThunderWaveTutor::
	lock
	faceplayer
	move_tutor MOVE_THUNDER_WAVE, Text_ThunderWaveTeach, Text_ThunderWaveWhichMon, EventScript_ThunderWaveDeclined, EventScript_ThunderWaveTaught, FLAG_0x2C1
	end

EventScript_ThunderWaveDeclined::
	msgbox Text_ThunderWaveDeclined
	release
	end

EventScript_ThunderWaveTaught::
	msgbox Text_ThunderWaveTaught
	release
	end

RockTunnel_B1F_EventScript_RockSlideTutor::
	lock
	faceplayer
	move_tutor MOVE_ROCK_SLIDE, Text_RockSlideTeach, Text_RockSlideWhichMon, EventScript_RockSlideDeclined, EventScript_RockSlideTaught, FLAG_0x2C2
	end

EventScript_RockSlideDeclined::
	msgbox Text_RockSlideDeclined
	release
	end

EventScript_RockSlideTaught::
	msgbox Text_RockSlideTaught
	release
	end

MtEmber_Exterior_EventScript_ExplosionTutor::
	lock
	faceplayer
	move_tutor MOVE_EXPLOSION, Text_ExplosionTeach, Text_ExplosionWhichMon, EventScript_ExplosionDeclined, EventScript_ExplosionTaught, FLAG_0x2C3
	goto EventScript_ExplosionTaught
	end

EventScript_ExplosionDeclined::
	msgbox Text_ExplosionDeclined
	release
	end

EventScript_ExplosionTaught::
	msgbox Text_ExplosionTaught
	release
	end

Route4_EventScript_MegaPunchTutor::
	lock
	faceplayer
	move_tutor MOVE_MEGA_PUNCH, Text_MegaPunchTeach, Text_MegaPunchWhichMon, EventScript_MegaPunchDeclined, EventScript_MegaPunchTaught, FLAG_0x2C4
	end

EventScript_MegaPunchDeclined::
	msgbox Text_MegaPunchDeclined
	release
	end

EventScript_MegaPunchTaught::
	msgbox Text_MegaPunchTaught
	release
	end

Route4_EventScript_MegaKickTutor::
	lock
	faceplayer
	move_tutor MOVE_MEGA_KICK, Text_MegaKickTeach, Text_MegaKickWhichMon, EventScript_MegaKickDeclined, EventScript_MegaKickTaught, FLAG_0x2C5
	end

EventScript_MegaKickDeclined::
	msgbox Text_MegaKickDeclined
	release
	end

EventScript_MegaKickTaught::
	msgbox Text_MegaKickTaught
	release
	end

EventScript_DreamEaterTutor::
	lock
	faceplayer
	move_tutor MOVE_DREAM_EATER, Text_DreamEaterTeach, Text_DreamEaterWhichMon, EventScript_DreamEaterDeclined, EventScript_DreamEaterTaught, FLAG_0x2C6
	end

EventScript_DreamEaterDeclined::
	msgbox Text_DreamEaterDeclined
	release
	end

EventScript_DreamEaterTaught::
	msgbox Text_DreamEaterTaught
	release
	end

EventScript_SoftboiledTutor::
	lock
	faceplayer
	move_tutor MOVE_SOFT_BOILED, Text_SoftboiledTeach, Text_SoftboiledWhichMon, EventScript_SoftboiledDeclined, EventScript_SoftboiledTaught, FLAG_0x2C7
	end

EventScript_SoftboiledDeclined::
	msgbox Text_SoftboiledDeclined
	release
	end

EventScript_SoftboiledTaught::
	msgbox Text_SoftboiledTaught
	release
	end

FuchsiaCity_EventScript_SubstituteTutor::
	lock
	faceplayer
	move_tutor MOVE_SUBSTITUTE, Text_SubstituteTeach, Text_SubstituteWhichMon, EventScript_SubstituteDeclined, EventScript_SubstituteTaught, FLAG_0x2C8
	end

EventScript_SubstituteDeclined::
	msgbox Text_SubstituteDeclined
	release
	end

EventScript_SubstituteTaught::
	msgbox Text_SubstituteTaught
	release
	end

SevenIsland_EventScript_SwordsDanceTutor::
	lock
	faceplayer
	move_tutor MOVE_SWORDS_DANCE, Text_SwordsDanceTeach, Text_SwordsDanceWhichMon, EventScript_SwordsDanceDeclined, EventScript_SwordsDanceTaught, FLAG_0x2C9
	end

EventScript_SwordsDanceDeclined::
	msgbox Text_SwordsDanceDeclined
	release
	end

EventScript_SwordsDanceTaught::
	msgbox Text_SwordsDanceTaught
	release
	end

PewterCity_Museum_1F_EventScript_SeismicTossTutor::
	lock
	faceplayer
	move_tutor MOVE_SEISMIC_TOSS, Text_SeismicTossTeach, Text_SeismicTossWhichMon, EventScript_SeismicTossDeclined, EventScript_SeismicTossTaught, FLAG_0x2CA
	end

EventScript_SeismicTossDeclined::
	msgbox Text_SeismicTossDeclined
	release
	end

EventScript_SeismicTossTaught::
	msgbox Text_SeismicTossTaught
	release
	end

EventScript_CounterTutor::
	lock
	faceplayer
	move_tutor MOVE_COUNTER, Text_CounterTeach, Text_CounterWhichMon, EventScript_CounterDeclined, EventScript_CounterTaught, FLAG_0x2CB
	end

EventScript_CounterDeclined::
	msgbox Text_CounterDeclined
	release
	end

EventScript_CounterTaught::
	msgbox Text_CounterTaught
	release
	end

EventScript_MetronomeTutor::
	lock
	faceplayer
	move_tutor MOVE_METRONOME, Text_MetronomeTeach, Text_MetronomeWhichMon, EventScript_MetronomeDeclined, EventScript_MetronomeTaught, FLAG_0x2CC
	end

EventScript_MetronomeDeclined::
	msgbox Text_MetronomeDeclined
	release
	end

EventScript_MetronomeTaught::
	msgbox Text_MetronomeTaught
	release
	end

EventScript_MimicTutor::
.if I_REUSABLE_TMS == FALSE
	goto_if_set FLAG_0x2CD, EventScript_MimicTaught
.endif
	msgbox Text_MimicTeach, MSGBOX_YESNO
	goto_if_eq VAR_0x800D, NO, EventScript_MimicDeclined
	call MoveTutor_EventScript_CanOnlyBeLearnedOnce
	goto_if_eq VAR_0x800D, NO, EventScript_MimicDeclined
	msgbox Text_MimicWhichMon
	setvar VAR_0x8005, MOVE_MIMIC
	call EventScript_ChooseMoveTutorMon
	lock
	faceplayer
	goto_if_eq VAR_0x800D, 0, EventScript_MimicDeclined
	removeitem ITEM_POKE_DOLL
.if I_REUSABLE_TMS == FALSE
	setflag FLAG_0x2CD
.endif
	goto EventScript_MimicTaught
	end

EventScript_MimicDeclined::
	msgbox Text_MimicDeclined
	release
	end

EventScript_MimicTaught::
	checkplayergender
	call_if_eq VAR_0x800D, MALE, EventScript_MimicTaughtMale
	call_if_eq VAR_0x800D, FEMALE, EventScript_MimicTaughtFemale
	release
	end

EventScript_MimicTaughtMale::
	msgbox Text_MimicTaughtMale
	return

EventScript_MimicTaughtFemale::
	msgbox Text_MimicTaughtFemale
	return

FourIsland_House1_EventScript_BodySlamTutor::
	lock
	faceplayer
	move_tutor MOVE_BODY_SLAM, Text_BodySlamTeach, Text_BodySlamWhichMon, EventScript_BodySlamDeclined, EventScript_BodySlamTaught, FLAG_0x2CE
	end

EventScript_BodySlamDeclined::
	msgbox Text_BodySlamDeclined
	release
	end

EventScript_BodySlamTaught::
	msgbox Text_BodySlamTaught
	release
	end

TwoIsland_CapeBrink_House_EventScript_StarterTutor::
	goto_if_questlog EventScript_ReleaseEnd
	special QuestLog_CutRecording
	lock
	faceplayer
	goto_if_set FLAG_0x2E1, CapeBrinkTutor_EventScript_TaughtAllMoves
	goto_if_set FLAG_TEMP_2, CapeBrinkTutor_EventScript_MoveJustTaught
	bufferleadmonspeciesname STR_VAR_1
	msgbox Text_UltimateMoveThatMon
	specialvar VAR_0x800D, CapeBrinkGetMoveToTeachLeadPokemon
	goto_if_eq VAR_0x800D, FALSE, CapeBrinkTutor_EventScript_NoLeadStarter
	copyvar VAR_0x8009, VAR_0x8005
	call_if_eq VAR_0x800C, DIR_NORTH, CapeBrinkTutor_EventScript_JumpInPlaceDown
	call_if_eq VAR_0x800C, DIR_SOUTH, CapeBrinkTutor_EventScript_JumpInPlaceUp
	call_if_eq VAR_0x800C, DIR_EAST, CapeBrinkTutor_EventScript_JumpInPlaceLeft
	call_if_eq VAR_0x800C, DIR_WEST, CapeBrinkTutor_EventScript_JumpInPlaceRight
	msgbox Text_AllowMeToTeachMonUltimateMove, MSGBOX_YESNO
	goto_if_eq VAR_0x800D, NO, CapeBrinkTutor_EventScript_DeclineMove
	call MoveTutor_EventScript_CanOnlyBeLearnedOnce
	goto_if_eq VAR_0x800D, NO, CapeBrinkTutor_EventScript_DeclineMove
	msgbox Text_LetMeConferUltimateMove
	closemessage
	fadescreen FADE_TO_BLACK
	goto CapeBrinkTutor_EventScript_ChooseMon

CapeBrinkTutor_EventScript_MoveJustTaught::
	msgbox Text_MakeBestUseOfMove
	release
	end

CapeBrinkTutor_EventScript_TaughtAllMoves::
	msgbox Text_FeelRejuvenated
	release
	end

CapeBrinkTutor_EventScript_TaughtMove::
	copyvar VAR_0x8005, VAR_0x8009
	specialvar VAR_0x800D, HasLearnedAllMovesFromCapeBrinkTutor
	goto_if_eq VAR_0x800D, TRUE, CapeBrinkTutor_EventScript_LearnedAllMoves
	msgbox Text_TaughtMove
	setflag FLAG_TEMP_2
	release
	end

CapeBrinkTutor_EventScript_LearnedAllMoves::
	msgbox Text_PassedOnEverythingIKnow
	setflag FLAG_0x2E1
	release
	end

CapeBrinkTutor_EventScript_ChooseMon::
	call EventScript_ChooseMoveTutorMon
	goto_if_eq VAR_0x800D, FALSE, CapeBrinkTutor_EventScript_DeclineMove
	goto CapeBrinkTutor_EventScript_TaughtMove
	end

CapeBrinkTutor_EventScript_JumpInPlaceDown::
	applymovement LOCALID_CAPE_BRINK_TUTOR, Movement_JumpInPlaceDown
	waitmovement 0
	return

CapeBrinkTutor_EventScript_JumpInPlaceUp::
	applymovement LOCALID_CAPE_BRINK_TUTOR, Movement_JumpInPlaceUp
	waitmovement 0
	return

CapeBrinkTutor_EventScript_JumpInPlaceLeft::
	applymovement LOCALID_CAPE_BRINK_TUTOR, Movement_JumpInPlaceLeft
	waitmovement 0
	return

CapeBrinkTutor_EventScript_JumpInPlaceRight::
	applymovement LOCALID_CAPE_BRINK_TUTOR, Movement_JumpInPlaceRight
	waitmovement 0
	return

CapeBrinkTutor_EventScript_DeclineMove::
	msgbox Text_YouRejectIt
	release
	end

CapeBrinkTutor_EventScript_NoLeadStarter::
	msgbox Text_JustMistaken
	release
	end

EventScript_ChooseMoveTutorMon::
	special ChooseMonForMoveTutor
	waitstate
	lock
	faceplayer
	return

MoveTutor_EventScript_CanOnlyBeLearnedOnce::
	textcolor NPC_TEXT_COLOR_NEUTRAL
	special DisableMsgBoxWalkaway
	signmsg
	msgbox Text_MoveCanOnlyBeLearnedOnce, MSGBOX_YESNO
	normalmsg
	call EventScript_RestorePrevTextColor
	return

MoveTutor_EventScript_OpenBox::
	chooseboxmon SELECT_PC_MON_MOVE_TUTOR
	waitstate
	lock
	faceplayer
	return

MoveTutor_AfterChooseBoxMon::
	waitstate
	special CanTeachMoveBoxMon
	waitstate
	return

Movement_JumpInPlaceDown:
	jump_in_place_down
	step_end

Movement_JumpInPlaceUp:
	jump_in_place_up
	step_end

Movement_JumpInPlaceLeft:
	jump_in_place_left
	step_end

Movement_JumpInPlaceRight:
	jump_in_place_right
	step_end
